[package]
name = "crdt"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
proptest = { version = "1.0", optional = true }
pretty_assertions = { version = "1.4", optional = true }

[features]
default = ["proptest"]
# When proptest feature is enabled, we include the proptest dependency and pretty_assertions
proptest = ["dep:proptest", "dep:pretty_assertions"]

[[example]]
name = "max_value"
required-features = ["proptest"]
